### ISSUE TITLE
Multiple Users? #featureRequest

### ISSUE THREAD

**Issue by dlashua** [Crewski/HANotify#1]
This is a GREAT component and it works flawlessly!

I'm curious... since the json file for storage calls this an "unnamed device", does this mean there may be room in the future to have notifications for more than one person?

**Comment by Crewski** [comment]
Multiple users as in different phones?  That's already in there.  You can rename the "unnamed device" if you want, though it may get overwritten right now.  If you want to send a notification to a specific user, use the target parameter.  If no target is provided, it'll send it to everyone you have registered.

**Comment by dlashua** [comment]
Yes! That's fantastic! Thank you!

**Comment by Crewski** [comment]
Just make sure to register each phone from the app.  👍
