### ISSUE TITLE
How to rename and remove registered devices?

### ISSUE THREAD

**Issue by jerrychong25** [Crewski/HANotify#12]
Hi all,

I would like to rename and remove registered devices with HANotify app.

But I not sure where to locate registered devices in HA.

Could anyone assist on this?

Thanks.

**Comment by mobidots** [comment]
@jerrychong25 There should be a `fcm_android_registrations.conf` file in your root config folder for HA

**Comment by jerrychong25** [comment]
> @jerrychong25 There should be a `fcm_android_registrations.conf` file in your root config folder for HA

@MobiDotS I tried to delete some registered devices in fcm_android_registrations.conf, then restart.

But it would restore back original records after I restart. 

Same goes to rename the device name.

Could advise how to resolve this?

Thanks.

**Comment by mobidots** [comment]
I have tested renaming the device, restarting, and deleting the device and restarting. Both persist the changes that I make. I am running HA 0.92.2

**Comment by jerrychong25** [comment]
I tested in 0.91.0 previously, and it is not working.

Anyway, I have upgraded to 0.94.1, and now able to rename and delete device successfully.

Thanks for the help.
