### ISSUE TITLE
[Feature request] Priority channel

### ISSUE THREAD

**Issue by syphernl** [Crewski/HANotify#5]
It would be nice to have a priority channels for notifications for instance that you can set it to ignore DND settings (e.g. security notifications).

**Comment by Crewski** [comment]
I can add a "channel" option to the fcm-android.py file......which would allow you to select/create a channel in Android (>=8.0).  Then it would be up to the user to select that channel in setting and allow it to override DND.  I'll get that set up when I get a chance.

**Comment by syphernl** [comment]
I've been looking into this as well. Even though I am unfamiliar with Kotlin I have been able to get a (rudimentary) implementation working. 

Currently it uses an optional data field called `priority` which can be set to `true`. 
It seems to work pretty well from my tests, I can make a PR for this (but the code could probably be optimized a bit though)
